spring:
  application:
    name: auth-service
server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

param:
  redirect-uri: http://localhost:3000/authorized
  bcrypt-key: test123